services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: backend
    ports:
      - "8080:8080"
    mem_limit: 128m  
    depends_on:
      - primary-api
      - secondary-api
      - toxiproxy

  primary-api:
    build:
      context: .
      dockerfile: primary-api/Dockerfile
    container_name: primary-api
    ports:
      - "8081:8081"

  secondary-api:
    build:
      context: .
      dockerfile: secondary-api/Dockerfile
    container_name: secondary-api
    ports:
      - "8082:8082"

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - backend

  toxiproxy:
    image: shopify/toxiproxy
    container_name: toxiproxy
    ports:
      - "8474:8474"
      - "8666:8666"

  toxiproxy-setup:
      image: curlimages/curl
      depends_on:
        - toxiproxy
      entrypoint: >
        sh -c "
        sleep 2 &&
        echo 'Creating Toxiproxy mapping...' &&
        curl -X POST http://toxiproxy:8474/proxies \
        -H 'Content-Type: application/json' \
        -d '{\"name\":\"primary\",\"listen\":\"0.0.0.0:8666\",\"upstream\":\"primary-api:8081\",\"enabled\":true}' &&
        echo 'Toxiproxy setup complete'
        "      